apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-microservice-frontend
spec:
  selector:
    matchLabels:
      app: sample-microservice-frontend
  template:
    metadata:
      labels:
        app: sample-microservice-frontend
    spec:
      containers:
      - name: sample-microservice-frontend
        image: salona1993/sample-mern-microservice:frontend-6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: sample-microservice-frontend-service
spec:
  selector:
    app: sample-microservice-frontend
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-profile-service
spec:
  selector:
    matchLabels:
      app: backend-profile-service
  template:
    metadata:
      labels:
        app: backend-profile-service
    spec:
      containers:
      - name: backend-profile-service
        image: salona1993/sample-mern-microservice:profile-service-9
        ports:
        - containerPort: 3002
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: profile-service-config
              key: PORT
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: profile-service-config
              key: MONGO_URL
          # You can also set other environment variables here
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend-profile-service
spec:
  selector:
    app: backend-profile-service
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hello-service
spec:
  selector:
    matchLabels:
      app: backend-hello-service
  template:
    metadata:
      labels:
        app: backend-hello-service
    spec:
      containers:
      - name: backend-hello-service
        image: salona1993/sample-mern-microservice:hello-service-6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-hello-service
spec:
  selector:
    app: backend-hello-service
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: bitnami/mongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service-config
data:
  PORT: "3002"
  MONGO_URL: "mongodb://mongo-service:27017/sample-db"
